import {GenericObject} from '@unicef-polymer/etools-types';
import {gddTranslatesMap} from '../../../utils/intervention-labels-map';
import {GDD_TABS} from '../../constants';

export const GDDCommentsItemsNameMap: GenericObject<string> = {
  attachments: 'ATTACHMENTS',
  'prc-document': 'PRC_REVIEW_DOC_TITLE',
  amendments: 'AMENDMENTS',
  details: 'DETAILS',
  financial: 'FINANCIAL',
  'fund-reservations': 'FUND_RESERVATIONS',
  'other-metadata': 'OTHER',
  'partner-details': 'PARTNER_DETAILS',
  'signatures-and-dates': 'SIGNATURES_DATES',
  'unicef-details': 'UNICEF_DETAILS',
  'document-details': 'DOCUMENT_DETAILS',
  'gender-equity-sustainability': 'GENDER_EQUITY_SUSTAINABILITY',
  'geographical-coverage': 'GEOGRAPHICAL_COVERAGE',
  risks: gddTranslatesMap.risks,
  'activity-timeframes': 'ACTIVITY_TIMEFRAMES',
  'programme-document-dates': 'PROGRAMME_DOC_DATES',
  'programmatic-visits': 'PROGRAMATIC_VISITS',
  'timing-overview': 'OVERVIEW',
  key_intervention: 'KEY_INTERVENTION',
  activity: 'ACTIVITY',
  'budget-summary': 'BUDGET_SUMMARY',
  'programme-management': gddTranslatesMap.management_budgets,
  'capacity-strengthening-costs': 'CAPACITY_STRENGTHENING_COST',
  'non-financial-contribution': 'PARTNER_NON_FINANCIAL_CONTRIBUTION',
  'supply-agreement': gddTranslatesMap.supply_items,
  indicator: 'INDICATOR',
  prp: 'PARTNER_REPORTING_REQUIREMENTS',
  eepm: 'EFFECTIVE_EFFICIENT_PROG_MGM',
  'programme-management-item': 'PROGRAMME_MANAGEMENT_ITEM',
  'activity-item': 'ACTIVITY_ITEM',
  'other-info': 'IMPORT_INFO'
};

export const GDDCommentsDescription: GenericObject<string> = {
  attachments: 'ATTACHMENTS_DESCRIPTION',
  'prc-document': 'PRC_REVIEW_DOC_DESCRIPTION',
  amendments: 'AMENDMENTS_DESCRIPTION',
  details: 'DETAILS_DESCRIPTION',
  financial: 'FINANCIAL_DESCRIPTION',
  'fund-reservations': 'FUND_RESERVATIONS_DESCRIPTION',
  'other-metadata': 'OTHER_DESCRIPTION',
  'partner-details': 'PARTNER_DETAILS_DESCRIPTION',
  'signatures-and-dates': 'SIGNATURES_DATES_DESCRIPTION',
  'unicef-details': 'UNICEF_DETAILS_DESCRIPTION',
  'document-details': 'DOCUMENT_DETAILS_DESCRIPTION',
  'gender-equity-sustainability': 'GENDER_EQUITY_SUSTAINABILITY_DESCRIPTION',
  'geographical-coverage': 'GEOGRAPHICAL_COVERAGE_DESCRIPTION',
  risks: `${gddTranslatesMap.risks}_DESCRIPTION`,
  'activity-timeframes': 'ACTIVITY_TIMEFRAMES_DESCRIPTION',
  'programme-document-dates': 'PROGRAMME_DOC_DATES_DESCRIPTION',
  'programmatic-visits': 'PROGRAMATIC_VISITS_DESCRIPTION',
  'timing-overview': 'OVERVIEW_DESCRIPTION',
  'budget-summary': 'BUDGET_SUMMARY_DESCRIPTION',
  'programme-management': `${gddTranslatesMap.management_budgets}_DESCRIPTION`,
  'capacity-strengthening-costs': 'CAPACITY_STRENGTHENING_COST_DESCRIPTION',
  'non-financial-contribution': 'PARTNER_NON_FINANCIAL_CONTRIBUTION_DESCRIPTION',
  'supply-agreement': `${gddTranslatesMap.supply_items}_DESCRIPTION`,
  'other-info': 'IMPORT_INFO_DESCRIPTION',
  'eepm-1': 'TITLE_1',
  'eepm-2': 'TITLE_2',
  'eepm-3': 'TITLE_3'
};

export const GDDComponentsPosition: GenericObject<string> = {
  attachments: GDD_TABS.Attachments,
  'prc-document': GDD_TABS.Attachments,
  amendments: GDD_TABS.Metadata,
  details: GDD_TABS.Metadata,
  financial: GDD_TABS.Metadata,
  'fund-reservations': GDD_TABS.Metadata,
  'other-metadata': GDD_TABS.Metadata,
  'partner-details': GDD_TABS.Metadata,
  'signatures-and-dates': GDD_TABS.Metadata,
  'unicef-details': GDD_TABS.Metadata,
  'document-details': GDD_TABS.Strategy,
  'gender-equity-sustainability': GDD_TABS.Strategy,
  'geographical-coverage': GDD_TABS.Strategy,
  risks: GDD_TABS.Strategy,
  'activity-timeframes': GDD_TABS.Timing,
  'programme-document-dates': GDD_TABS.Timing,
  'programmatic-visits': GDD_TABS.Timing,
  'timing-overview': GDD_TABS.Timing,
  'key-intervention': GDD_TABS.Workplan,
  activity: GDD_TABS.Workplan,
  'budget-summary': GDD_TABS.Workplan,
  'programme-management': GDD_TABS.Workplan,
  'capacity-strengthening-costs': GDD_TABS.Workplan,
  'non-financial-contribution': GDD_TABS.Workplan,
  'supply-agreement': GDD_TABS.Workplan,
  indicator: GDD_TABS.Workplan,
  prp: GDD_TABS.Timing,
  eepm: GDD_TABS.Workplan,
  'other-info': GDD_TABS.Metadata
};
